# Generated by Django 2.2.14 on 2021-07-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image2',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
