# Generated by Django 2.2.14 on 2021-07-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210718_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='files',
        ),
        migrations.AddField(
            model_name='item',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('H', 'house'), ('C', 'comunication'), ('O', 'other')], max_length=1),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
