# Generated by Django 2.2.14 on 2021-07-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
