# Generated by Django 2.2.14 on 2021-08-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_itemimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
