# Generated by Django 2.2.14 on 2021-09-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210904_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('H', 'house'), ('C', 'comunication'), ('O', 'other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(max_length=100000, null=True),
        ),
    ]
