# Generated by Django 2.2.14 on 2021-09-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210920_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='batary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='camera',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
