# Generated by Django 2.2.14 on 2021-09-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210920_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='access',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='screen',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='item',
            name='simcard',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='batary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='camera',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='memory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
