# Generated by Django 2.2.14 on 2021-09-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210920_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='publish',
            field=models.DateField(null=True),
        ),
    ]
