# Generated by Django 2.2.14 on 2021-09-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_item_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
