# Generated by Django 2.2.14 on 2021-09-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20210924_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='supplies',
            field=models.IntegerField(null=True),
        ),
    ]
